# install.packages("dplyr")
# install.packages("rgl")
# install.packages("class")
# install.packages("rpart")
# install.packages("rpart.plot")
# install.packages("e1071")
# install.packages("ROCR")
# install.packages('arules')
# install.packages('arulesViz')

library("dplyr")
library("rgl")
library("class")
library("rpart")
library("rpart.plot")
library("e1071")
library("ROCR")
library('arules')
library('arulesViz')