---
title: "Midterm Practise"
author: "Ethan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, include = TRUE,
                      fig.align = "center",  out.width = "80%")
```

## Question 1
### Question 1.1
Answer question 1.1 here.

```{r}
heights <- read.csv("../data/heights.csv", header=TRUE, stringsAsFactors = TRUE)
# heights
sum(is.na(heights))

apply(heights, 2, function (x) sum(is.na(x)))

tapply(heights$earn, heights$sex, mean)

```

### Question 1.2
Answer question 1.2 here.

```{r}
hist(heights$earn, freq=FALSE,
    main = "Histogram of Earnings", xlab = "Earnings per annum",
    col = "indianred", border = "white")

plot(heights$age, heights$earn, pch=2)
abline(reg=lm(earn~age, data=heights), col="gray60", lty="dashed")



barplot(tapply(heights$earn, heights$race, mean))

boxplot(heights$earn~heights$race)
```

## Question 2

```{r}
# install.packages("readr")
library(readr)
heights <- read_csv("../data/heights.csv", col_types = "infiif") # with underscore, specify column types
heights

# install.packages("readxl")
library(readxl)
read_excel("../data/read_excel_01.xlsx", range="C6:E8", col_names=FALSE)


file_name <- "../data/UNESCAP_population_2010_2015.xlsx"
female_0_4 <- read_excel("../data/UNESCAP_population_2010_2015.xlsx", sheet=3)

library(stringr)
library(tidyverse)
sheet_names <- excel_sheets(file_name)
female_0_4 %>% 
  mutate(age=str_split(excel_sheets(file_name)[3], ",", simplify = TRUE)[3],
         age=str_trim(age))

# Check how to read in by group in lecture notes
```
```{r}
hawkers <- readRDS("../data/hawker_ctr_raw.rds")
str(hawkers[[1]][[7]])

hawkers_116 <- hawkers[[1]][-1]

hawkers_116[[1]]$ADDRESSSTREETNAME

# street_name <- sapply(hawkers_116, function(x) x$ADDRESSSTREETNAME)
# postal_code <- sapply(hawkers_116, function(x) x$ADDRESSPOSTALCODE)
# name <- sapply(hawkers_116, function(x) x$NAME)
# coordinates <- sapply(hawkers_116, function(x) x$XY)
# 
# hawkers_df <- data.frame(postal_code, name, coordinates)

hawkers_df <- do.call(rbind, lapply(hawkers_116, as.data.frame))

hawkers_df 
# street_name
```

```{r}
library(jsonlite)
all_lines <- readLines("../data/read_json_02.txt")
json_list <- lapply(all_lines, fromJSON)
json_list

convert_2_df <- function(x) {
  lower = ifelse("lower" %in% x$shelf, 1, 0)
  middle = ifelse("middle" %in% x$shelf, 1, 0)
  upper = ifelse("upper" %in% x$shelf, 1, 0)
  data.frame(fruit = x$fruit, price = x$price, lower, middle, upper)
}
df_row <- lapply(json_list, convert_2_df)
df_row
df_fruit <- rbind(df_row[[1]], df_row[[2]], df_row[[3]])
df_fruit

```

```{r}
library(nycflights13)
data(flights)

flights

flights %>% mutate(across(year:time_hour, 
                          function (x) sum(is.na(x)))) %>% slice_head()

# apply(flights, 2, function (x) sum(is.na(x)))

```

```{r}
df1 <- tibble(x = 1:3)
df2 <- tibble(y = 3:1)
bind_cols(df1, df2)
df1 <- tibble(x = 1:3)
df2 <- tibble(x = 3:1)
bind_rows(df1, df2)


df1 <- data.frame(x = c(5, 6, 7),     
                     y = c(1, 1, 1)) 
  
# Data frame 2 
df2 <- data.frame(x = c(2, 3, 4),        
                     y = c(2, 2, 2)) 

intersect(df1, df2)
union(df1, df2)
union_all(df1, df2)
setdiff(df1, df2)
setdiff(df2, df1)
symdiff(df1, df2)

```

```{r}
ggplot(data = mtcars, aes(x = mpg, y = wt, label = rownames(mtcars), color = am)) +
  geom_point() +
  geom_text_repel(size=3) + 
  labs(title = "Miles/gallon against Weight", 
       x = "Miles/(US) gallon", y = "Weight (1000 lbs)", color = "Transmission")
```