---
title: "Tutorial Week 07"
author: "Ethan Keck"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, include = TRUE,
                      fig.align = "center",  out.width = "80%")
```

## Question 1
### Question 1.1
Answer question 1.1 here.

```{r}
# setwd("C:\\Users\\Keck\\Documents\\GitHub\\devcontainers-rstudio\\NUS Stuff\\DSA2101\\tutorial")
library(readxl)
library(tidyverse)
library(lubridate)
library(stringr)
tourist <- tibble(read_excel('../Data/tourist.xlsx', 
  range="A10:G26", col_name = TRUE)) %>% 
  filter(!row_number() %in% c(1, 11, 16))

months <- rev(gsub("2022 ", "", colnames(tourist)[-1]))
# year=as.numeric(gsub(paste0(months, collapse = "|"), "", Year_Month)),
# month= factor(gsub("2022 ", "", Year_Month), levels = months),
# duration=gsub("\\(Number\\)", "",duration)) %>%
# tourist %>% pivot_longer(`2022 Dec`:`2022 Jul`, names_to="year_month", values_to="arrivals")

qn1_1 <- tourist %>% 
  mutate(k=row_number()) %>%
  gather(`2022 Dec`:`2022 Jul`, key="year_month", value="arrivals") %>% 
  separate(year_month, into= c("year", "month"), " ") %>%
  rename(duration="Data Series") %>%
  mutate(year=as.integer(year), month=factor(month, levels = months)) %>% 
  arrange(month) %>% relocate(k, duration, year, month, arrivals)
glimpse(qn1_1)
```

### Question 1.2

```{r}
qn1_2 <- qn1_1 %>% 
  mutate(mom_change
         =round(100*(arrivals-lag(arrivals, 13))/lag(arrivals, 13), 1)) %>%
  na.omit()
head(qn1_2, 2)
```

## Question 2
### Question 2.1
```{r eval=FALSE, include=FALSE}
# install.packages("tidytuesdayR")
```

```{r}
# library(nberwp)
papers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-28/papers.csv')
authors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-28/authors.csv')
programs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-28/programs.csv')
paper_authors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-28/paper_authors.csv')
paper_programs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-28/paper_programs.csv')

# 
joined_df <- left_join(papers, paper_authors) %>%
  left_join(authors) %>%
  left_join(paper_programs) %>%
  left_join(programs)%>%
  mutate(
    catalogue_group = str_sub(paper, 1, 1),
    catalogue_group = case_when(
      catalogue_group == "h" ~ "Historical",
      catalogue_group == "t" ~ "Technical",
      catalogue_group == "w" ~ "General"
    ),
    .after = paper
  )

str(joined_df)
```

### Question 2.2

```{r}
# qn2_2 <- joined_df %>% filter(program_category == "Finance") %>%
#   select(year, program_desc, program_category) %>% 
#   group_by(year, program_desc) %>% mutate(n=n()) %>% ungroup() %>% distinct()

qn2_2 <- papers %>% left_join(paper_programs, by="paper") %>% 
  left_join(programs, by="program") %>%
  filter(program_category=="Finance") %>% 
  count(year, program_desc, program_category)
glimpse(qn2_2)
```
### Question 2.3

```{r}
library(ggplot2)

plot1 <- qn2_2 %>% filter(program_desc=="Corporate Finance")
plot2 <- qn2_2 %>% filter(program_desc=="Asset Pricing")

plot(plot1$year, plot1$n, type="l", color="indianred", lwd=3)
lines(plot2$year, plot2$n, color="grey")
# legend()

ggplot() +
    geom_line(data = plot1, aes(x=year, y=n), color = "red") +
    geom_line(data = plot2, aes(x=year, y=n), color = "blue") +
    labs(title = "Number of Finance papers from 1978 to present",
    x = "Year", y = "Number of paper") +
    theme_classic() +
    theme(text = element_text(size=15))
```
- Covid-19?

### Question 2.4

```{r}
qn2_4 <- papers %>% left_join(paper_authors, by="paper") %>% 
  left_join(authors, by="author") %>% select(paper, year, name)
glimpse(qn2_4)
```
### Question 2.5

```{r}
# qn2_4 %>% mutate(decade = case_when(year <= 1979 - ""))
qn2_5 <- qn2_4 %>% select(paper, year, name) %>%
  mutate(year=paste(floor(year/10), "0s", sep="")) %>%
  rename(decade = year) %>% group_by(paper, decade) %>%
  summarize(n = n()) %>% ungroup() %>%
  group_by(decade) %>% summarize(avg_n_authors = mean(n))
head(qn2_5,3)
```

