---
title: "Tutorial Week 3"
author: "Ethan Keck"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, include = TRUE,
                      fig.align = "center",  out.width = "80%")
```

## Question 1

```{r}
data(airquality)
no_months <- length(unique(airquality$Month))
no_months
# 5
```

### Question 2

```{r}
# df_missing <- airquality[!complete.cases(airquality),]  
# no_missing <- nrow(df_missing)
no_missing <- sum(is.na(airquality))
no_missing
```

## Question 3

```{r}
df <- airquality[complete.cases(airquality),]
df_summer <- df[df$Month < 7,]
df_fall <- df[!df$Month < 7,]
head(df_summer)
unique(df_summer$Month)
head(df_fall)
unique(df_fall$Month)
```

## Question 4
```{r}
df$season <- sapply(df$Month, (function (x) ifelse(x<7, "Summer", "Fall")))
df$season <- as.factor(df$season)
str(df)
table(df$Month, df$season)
stats <- tapply(df$Temp, df$season, FUN = summary)
stats
```
## Question 5
```{r}
# df$Month <- factor(month.abb[df$Month], levels = month.abb)
df$Month <- factor(month.abb[df$Month], levels = c('May', 'Jun', 'Jul', 'Aug', 'Sep'))
str(df)
table(df$Month, df$season)
```
```{R}
library(ggplot2)
 ggplot(df, aes(x = df$Month, y = df$Temp)) +
     geom_boxplot(fill='#A4A4A4', color="black", coef=1.5) +
     stat_boxplot(geom ='errorbar') +
     labs(title = "Monthly Temperature in New York",
     x = "Months",
     y = "Temperature") +
    geom_jitter(position=position_jitter(0.1))
# boxplot(df$Temp ~ df$Month, xlab = "Month",
#    ylab = "Temperature (degrees F)",
#   main = "Monthly Temperature in New York")
```
