---
title: "Tutorial Week X"
author: "student's name"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, include = TRUE,
                      fig.align = "center",  out.width = "80%")
```

```{r}
library(tidyverse)
library(ggplot2)
library(stringr)
library(lubridate)
```


```{r}
olympics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/olympics.csv')

regions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/regions.csv')

```
## Question 1
### Question 1.1
Answer question 1.1 here.

```{r}
olympics %>% filter(tolower(season) == 'summer', between(year, 1896, 2016)) %>%
  group_by(year) %>%
  summarize(n_nations = n_distinct(noc),
            n_events = n_distinct(event), .groups = "drop") %>% 
  ggplot() + 
  geom_line(aes(x=year, y=n_nations), color = "gray22", linewidth = 1.5) +
  geom_line(aes(x=year, y=n_events), color = "indianred4", linewidth = 1.5) +
  labs(title = "Number of Events and Nations in Summer Olympics", x = "", y = "") +
  annotate("text", x = 2010, y = c(180, 280), 
           label = c("Nations", "Events"), color = c("gray22", "indianred4")) +
  theme_minimal()
  

```

### Question 1.2
Answer question 1.2 here.

```{r}
summer_top_5 <- olympics %>% filter(year == 2016, tolower(season) == 'summer') %>%
  select(noc, year, event, medal) %>% 
  distinct() %>% rename(country=noc) %>%
  group_by(country) %>%
  summarize(gold = sum(tolower(medal) == 'gold', na.rm=TRUE)) %>%
  arrange(desc(gold)) %>% head(5) %>% .$country

summer_top_5
```
### Question 1.3
```{r}
golds_top_5 <- olympics %>% filter(year >= 2000, noc %in% summer_top_5, tolower(season)=='summer') %>%
  select(noc, year, event, medal) %>% 
  distinct %>% rename(country = noc) %>% 
  group_by(year, country) %>%
  summarize(gold = sum(tolower(medal) == 'gold', na.rm=TRUE))

df_labels <- golds_top_5 %>% filter(year == 2016) %>%
    left_join(regions, by = c("country" = "NOC"))
  
ggplot(data = golds_top_5, aes(x=year, y=gold)) +
  geom_point(aes(col = country), size = 5, show.legend = FALSE) +
  geom_line(aes(col=country), show.legend = FALSE) +
  geom_text(data = df_labels, aes(label = region),
            hjust = "left", nudge_x = 0.3, size = 3.5) + 
  labs(x = "", y = "Number of golds received", color = "Region",
       title = "Gold medals received for selected countries, by year") + 
  scale_x_continuous(breaks = seq(2000, 2016, 4), limits = c(1999, 2017.5)) +
  scale_y_continuous(breaks = seq(0, max(golds_top_5$gold), 10), limits = c(0, 52.5)) +
  theme_minimal()

```
### Question 1.4

```{r}
ranks_top_5 <- olympics %>% filter(year >= 2000, tolower(season)=='summer') %>%
  select(noc, year, event, medal) %>% 
  distinct %>% rename(country = noc) %>% 
  group_by(year, country) %>%
  summarize(gold = sum(tolower(medal) == 'gold', na.rm=TRUE), .groups = "drop") %>%
  group_by(year) %>% 
  mutate(rank = min_rank(desc(gold))) %>%  arrange(rank) %>%
  filter(country %in% summer_top_5) 
ranks_top_5
```
### Question 1.5

```{r}
df_labels <- ranks_top_5 %>% filter(year == 2016) %>%
  left_join(regions, by = c("country" = "NOC")) 

ggplot(data= ranks_top_5, aes(x = year, y = rank)) +
    geom_point(aes(color = country), size = 4, show.legend = FALSE) +
    geom_line(aes(color = country), show.legend = FALSE) +
  geom_text(data = df_labels, aes(label = region),
            hjust = "left", nudge_x = 0.5, size = 3.5) +
  labs(x = "", y = "",
       title = "Rankings of golds received, by year",
       subtitle = "for countries that won the most golds in 2016",
       caption = "Note: dplyr::min_rank() was used to compute country rankings") +
  scale_y_continuous(trans = "reverse", breaks = seq(1, 10, 1)) +
  scale_x_continuous(breaks = seq(2000, 2016, 4), limits = c(2000, 2018))

```
## Question 2

```{r}

```
